### ISSUE TITLE
Docker Container

### ISSUE THREAD

**Issue by jonathan-scholbach** [nun-singet-und-seid-froh/nun-singet-und-seid-froh#18]
We want to have a docker container that contains all necessary tools to ease the process of installing dependencies for contributing to the project.

**Comment by fibsifan** [comment]
I have started a repository for a docker container: [nun-singet-und-seid-froh/docker-lilypond](https://github.com/nun-singet-und-seid-froh/docker-lilypond).
I also created a team on dockerhub. The Container is built to [nunsingetundseidfroh/lilypond](https://hub.docker.com/r/nunsingetundseidfroh/lilypond).
