### ISSUE TITLE
Include Commentary in Sheet

### ISSUE THREAD

**Issue by jonathan-scholbach** [nun-singet-und-seid-froh/nun-singet-und-seid-froh#28]
Commentaries should be created from a commentary.tex file in the score's leaf folder.
To get this working, we have to decide about the following:
+ Pagination of commentaries (subsequent page numbers, or new begin of page numbering, for instance in roman numbers)
+ Versioning of commentaries (independent from score's version=

Besides that we have to do the following thing
+ create .tex template for commentaries
+ include XeLaTex in our docker container (XeLaTex instead of simple LaTex is required to typeset the commentary in EB Garamond)
+ update the Makefile accordingly
+ add the commenatary's version as a field on Sheet model in jubilo
+ update the automatic deployment to check for the need of PUT request in case the commentary's version has changed (even if the score has not)

**Comment by krono** [comment]
Hi, 

(im just lurking, but I just read:
>     * include XeLaTex in our docker container (XeLaTex instead of simple LaTex is required to typeset the commentary in EB Garamond)
) 
Why do you need XeLaTeX for EB Garamond? It works well with normal pdfLaTeX and LuaLaTeX.
I can help.

**Comment by krono** [comment]
Additional idea:  
The [markdown](https://ctan.org/pkg/markdown) package allows to include most Markdown files in LaTeX directly. Best used with LuaLaTeX. 

Thus just the `commentary.md` file would be necessary and the rest could be a template.

**Comment by jonathan-scholbach** [comment]
Closing the issue, because it is done now.
